#!/usr/bin/env bash
# Generates:
#   .env.deploy          — read by docker-compose.yml's own interpolation
#   api-server/.env       — read by the api-server + build-worker containers
#   reverse-proxy/.env    — read by the reverse-proxy container
#
# Idempotent by REFUSING to overwrite a file that already exists — same
# reasoning as the repo root's own scripts/lib/generate-env.sh: regenerating
# JWT_ACCESS_SECRET or ENCRYPTION_KEY on a second run invalidates every
# existing session and makes every already-encrypted GitHub token
# undecryptable. Delete the specific file yourself first if you genuinely
# want it regenerated.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_ENGINE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=./common.sh
source "${SCRIPT_DIR}/common.sh"

# Args: DOMAIN POSTGRES_PASSWORD MINIO_ROOT_PASSWORD (all required, passed
# in by install.sh — one source of truth for each across every generated
# file, same as the repo root's own generate-env.sh).
DOMAIN="${1:?generate-env.sh requires DOMAIN as \$1}"
POSTGRES_PASSWORD="${2:?generate-env.sh requires POSTGRES_PASSWORD as \$2}"
MINIO_ROOT_PASSWORD="${3:?generate-env.sh requires MINIO_ROOT_PASSWORD as \$3}"

write_if_absent() {
  local path="$1"
  local content="$2"
  if [[ -f "${path}" ]]; then
    log_warn "${path} already exists — leaving it untouched (delete it yourself first if you want it regenerated)."
    return
  fi
  echo "${content}" > "${path}"
  chmod 600 "${path}"
  log_ok "Wrote ${path}"
}

generate_all_env_files() {
  local jwt_access jwt_refresh encryption_key

  jwt_access="$(random_hex 32)"
  jwt_refresh="$(random_hex 32)"
  encryption_key="$(random_hex 32)"

  # --- .env.deploy ---------------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/.env.deploy" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh — read by docker-compose.yml
# itself (build args, container environment), not by application code.
DOMAIN=${DOMAIN}
POSTGRES_USER=dreamer
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=dreamer
MINIO_ROOT_USER=dreamer
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
S3_BUCKET=dreamer-outputs
NEXT_PUBLIC_API_BASE_URL=https://api.${DOMAIN}
NEXT_PUBLIC_SOCKET_URL=https://api.${DOMAIN}
BUILD_WORKER_CONCURRENCY=5
EOF
)"

  # --- api-server/.env -------------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/api-server/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
# Lines marked TODO are placeholders this script cannot generate for you
# (they need a GitHub App and, optionally, a Resend account of your own).
# api-server WILL crash-loop until you fill these in — see the final
# summary install.sh prints. That's expected: env.ts fails fast on boot
# specifically so a misconfiguration shows up immediately in
# \`docker compose logs api-server\`, not three requests into production.

NODE_ENV=production
PORT=8000
FRONTEND_URL=https://${DOMAIN}

DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
DATABASE_CA_CERT=not-used-in-production-see-lib-prisma-ts
REDIS_URL=redis://redis:6379
REDIS_BUILDER_URL=redis://redis-builder:6379

DEPLOYMENT_MODE=docker
DOCKER_BUILD_ENGINE_IMAGE=dreamer-build-engine:local
DOCKER_NETWORK=dreamer-local

AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=dreamer
AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
S3_ENDPOINT_URL=http://minio:9000
S3_FORCE_PATH_STYLE=true
S3_BUCKET=dreamer-outputs

JWT_ACCESS_SECRET=${jwt_access}
JWT_REFRESH_SECRET=${jwt_refresh}
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL_DAYS=7
ENCRYPTION_KEY=${encryption_key}

# TODO — create a GitHub App: https://github.com/settings/apps/new
GITHUB_APP_CLIENT_ID=
GITHUB_APP_CLIENT_SECRET=
GITHUB_APP_ID=
GITHUB_APP_SLUG=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_WEBHOOK_SECRET=

API_PUBLIC_URL=https://api.${DOMAIN}
BASE_DOMAIN=${DOMAIN}

# TODO — https://resend.com, verify a sending domain, paste the API key
RESEND_API_KEY=
EMAIL_FROM="Dreamer <dreamer@${DOMAIN}>"
EOF
)"

  # --- reverse-proxy/.env -----------------------------------------------
  write_if_absent "${LOCAL_ENGINE_ROOT}/reverse-proxy/.env" "$(cat <<EOF
# Generated by scripts/lib/generate-env.sh.
BASE_DOMAIN=${DOMAIN}
BASE_PATH=http://minio:9000/dreamer-outputs/__outputs
DATABASE_URL=postgresql://dreamer:${POSTGRES_PASSWORD}@postgres:5432/dreamer
REDIS_URL=redis://redis:6379
EOF
)"
}

generate_all_env_files
